### ISSUE TITLE
There's a way to ignore warnings without disable fail-on-error flag ?

### ISSUE THREAD

**Issue by qwa-fernandonissizaki** [dbelyaev/action-checkstyle#10]
I need to bypass warning checkstyle appointments.
On my project we started to use checkstyle and some issues we will treat afterwards.

**Comment by dbelyaev** [comment]
Did you check https://github.com/dbelyaev/action-checkstyle#level  parameter?
Or you do not want to have warnings at all?

**Comment by qwa-fernandonissizaki** [comment]
Yes, I've checked this flag, but what I want is, when checkstyle process find some warning issues, do not break the process, only if it find some error level.

I tried to set the level to error, but it just not print warning issues, and it's not what I want.

Flagging fail_on_error to true, than, checkstyle fails even in warning issues.

**Comment by dbelyaev** [comment]
This action is using an powerful tool called reviewdog to report status checks on GItHub pull request. Unfortunately, at this moment it does not support different severity levels for GitHub check reporting - https://github.com/reviewdog/reviewdog/issues/343.

**Comment by dbelyaev** [comment]
Closing this issue as it is stale now and answer has been added to original question.
