### ISSUE TITLE
Support suppressions?

### ISSUE THREAD

**Issue by asteele0** [dbelyaev/action-checkstyle#99]
#### Describe Problem
I need to be able to have a way to suppress certain pre-existing warnings when running Checkstyle.

Does this action support that?

As I understand it, the usual way of doing this is via a `suppressions.xml` file.

Links
* https://github.com/checkstyle/checkstyle/blob/master/config/suppressions.xml
* https://juliangamble.com/blog/2012/03/10/running-checkstyle-at-full-throttle-on-a-legacy-codebase/

**Comment by dbelyaev** [comment]
Yes, suppressions are supported by this action.

### Suppressions via suppression configuration file

You will need to configure the `<module name="SuppressionFilter">` module entry in your Checkstyle configuration (referencing the suppression configuration file). Then, supply suppression configurations for specific checks and files within this file. Docs from Checkstyle with examples on how to configure such a file can be found here: [https://checkstyle.org/filters/suppressionfilter.html](https://checkstyle.org/filters/suppressionfilter.html).

I have just added an example PR in a test repository to demonstrate how to configure the action to use your custom Checkstyle configuration with suppressions. You can find this PR here: [https://github.com/dbelyaev/action-checkstyle-tester/pull/15](https://github.com/dbelyaev/action-checkstyle-tester/pull/15) and the corresponding [changeset](https://github.com/dbelyaev/action-checkstyle-tester/compare/example/non-compliant-google-style-code...example/using-suppressions-config).

It includes a custom Checkstyle configuration (actually, a copy of the `google_checks.xml`) that is [referencing](https://github.com/dbelyaev/action-checkstyle-tester/blob/2067a7a460ddc0ed9dde40e9d61cdced4f20a5be/google_checks.xml#L33-L37) the custom [checkstyle-suppressions.xml](https://github.com/dbelyaev/action-checkstyle-tester/pull/15/files#diff-755559798e55a858f48393aca4522ff99f8d40d704d69978fc1806102e32ebea) file with a configuration to suppress `JavadocStyleCheck` and `IndentationCheck` checks.

You can see how it affects the output:

- [An example PR with non-compliant Google style code without any suppressions](https://github.com/dbelyaev/action-checkstyle-tester/pull/9).
- [An example PR with non-compliant Google style code with suppressions (`JavadocStyleCheck` and `IndentationCheck`)](https://github.com/dbelyaev/action-checkstyle-tester/pull/15).

### Inline suppression annotations directly in code-base

It is also possible to use inline code annotations to suppress Checkstyle warnings for specific parts of the code (methods or entire classes). This can be done by following the Checkstyle docs: [https://checkstyle.org/filters/suppresswarningsfilter.html#SuppressWarningsFilter](https://checkstyle.org/filters/suppresswarningsfilter.html#SuppressWarningsFilter).

**Comment by asteele0** [comment]
Awesome, thank you very much for the detailed response!
